### ISSUE TITLE
requirements.txt should include 'click'

### ISSUE THREAD

**Issue by divv** [tlelson/tlx#8]
```
get-aws-creds --help

Traceback (most recent call last):
  File "d:\users\david.tout\appdata\local\programs\python\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\users\david.tout\appdata\local\programs\python\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\david.tout\Envs\dynamo\Scripts\get-aws-creds.exe\__main__.py", line 5, in <module>
  File "d:\users\david.tout\envs\dynamo\lib\site-packages\tlx\util\cli_apps\get_aws_creds.py", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Comment by tlelson** [comment]
Thanks Divv, fixed with trivial tests of all CLI apps.
7c6ea0c
